### ISSUE TITLE
后台配置了sql，或内容，但 ctx.Data，和 ctx.Remark  没拿到东西

### ISSUE THREAD

**Issue by Jxika** [NewLifeX/AntJob#12]
![image](https://github.com/NewLifeX/AntJob/assets/39694137/c52778a5-558b-4883-a1cf-3b982019324b)
但
![image](https://github.com/NewLifeX/AntJob/assets/39694137/f0b2bab6-79f7-43e9-9f29-b2878a8ae3fb)
 没 1-100,2-2

**Comment by Jxika** [comment]
通过  ctx.Handler.Job.Data 能拿到数据，但发现另一个bug，在克隆job时，类名没带上

**Comment by nnhy** [comment]
感谢发现bug，欢迎提交PR
