### ISSUE TITLE
Job.Cron为空，出错问题

### ISSUE THREAD

**Issue by guiqiang123** [NewLifeX/AntJob#13]
我新加一个程序，然后引入最新版本得NewLife.AntJob，然后使用Job.Cron这个字段，说是IJob未定义Cron字段，但是下载最新版本得AntJob源码，运行AntJob.Server和AntJob.Web，里面就需要Cron字段，如果Cron为空，就会报错
![XPHKZQY3ZUJO 1_JT}E ~KH](https://github.com/NewLifeX/AntJob/assets/24471990/58347b85-01f5-4da1-a212-5b3f7023725e)

![`8E7I4N@M8U 2MG7 6ZY3X7](https://github.com/NewLifeX/AntJob/assets/24471990/916b255f-baad-4b45-b6ac-041df89af91d)

**Comment by Soar360** [comment]
用源代码的方式引入，nuget 没更新了。

**Comment by guiqiang123** [comment]
用生成得dll，导入项目呗

**Comment by Soar360** [comment]
都可以。我的做法是直接添加源代码的项目引用。

**Comment by guiqiang123** [comment]
是引用AntJob和AntJob.Extensions么，还是只引用AntJob就行？

**Comment by nnhy** [comment]
问题在于AntJob的自动发布脚本除了问题，最近几个月都没有发布新版本。
今天已经修复，可以试试引用新的nuget包
