### ISSUE TITLE
以后是否可能支持设置多任务之间的执行顺序

### ISSUE THREAD

**Issue by Jxika** [NewLifeX/AntJob#14]
石头哥你好，在生产中出现了 A任务执行完后，自动执行B任务的场景。因为A任务执行的时间长短不确定，所以很难设置B任务的开始时间。希望以后蚂蚁调度可以支持设置某任务执行完后，可以自动触发其他任务的配置。

**Comment by nnhy** [comment]
AntJob新版本已经支持Delay延迟。
针对你的问题，可以在B任务执行时，检测数据源，判断A是否已完成，如果前置数据未就绪，那么B可以调用Delay(DateTime.Now.AddMinute(1)) 并return 0，告诉平台，该任务需要延迟到1分钟后执行。
那么，该任务在平台标记为“延迟”状态。等1分钟后再次执行，知道前置数据已就绪。
总的重试次数等于作业的错误重试数配置。

**Comment by nnhy** [comment]
AntJob用了4年的时间来设计作业任务之间的依赖关系，多次参考Hadoop调度，最终都因为过于复杂而失败。
在7月份的时候，突发奇想，既然做不到简单灵活的前置任务检测，那么我们可以学到它的灵魂。
前置不满足的时候，任务延期执行，而前置检测的工作，交给用户，这就是Delay产生的根源。

**Comment by Jxika** [comment]
从代码层面检测确实能解决，但数据流转因为是跨部门合作的，且数据没有设置多余的状态，都是业务方面的数据，任务之间的依赖关系还会随时改。

**Comment by nnhy** [comment]
我们实际工作中也是这样的。
B应用依赖很多个数据源，来自多个不同部门的系统。
然后我们在B任务开头就检查这些表，所需要的数据是否已就绪，如果没有就绪，那就设置B当前任务Delay延迟

**Comment by darkmice** [comment]
Delay延迟是不是前置数据没有准备好，就可以一直Delay下去直到数据准备好

**Comment by nnhy** [comment]
> Delay延迟是不是前置数据没有准备好，就可以一直Delay下去直到数据准备好

对！
是不是Delay，你说了算，因为逻辑复杂，只有用户代码才能满足各种场景需求。
而AntJob要做的，就是Delay然后重试。

Delay的参数，可以指定下一次什么时候重试，你还可以做成滑动间隔。

**Comment by darkmice** [comment]
> > Delay延迟是不是前置数据没有准备好，就可以一直Delay下去直到数据准备好
> 
> 对！ 是不是Delay，你说了算，因为逻辑复杂，只有用户代码才能满足各种场景需求。 而AntJob要做的，就是Delay然后重试。
> 
> Delay的参数，可以指定下一次什么时候重试，你还可以做成滑动间隔。

我之前也有做一个类似的任务调度，每个任务都有前置数据准备就绪才进入工作， 这个前置数据准备就绪的时间不确定的，只能任务的开始时间到了之后，定时（默认30秒）去检测前置数据是否就绪，直到数据就绪为止。

**Comment by nnhy** [comment]
> > > Delay延迟是不是前置数据没有准备好，就可以一直Delay下去直到数据准备好
> > 
> > 
> > 对！ 是不是Delay，你说了算，因为逻辑复杂，只有用户代码才能满足各种场景需求。 而AntJob要做的，就是Delay然后重试。
> > Delay的参数，可以指定下一次什么时候重试，你还可以做成滑动间隔。
> 
> 我之前也有做一个类似的任务调度，每个任务都有前置数据准备就绪才进入工作， 这个前置数据准备就绪的时间不确定的，只能任务的开始时间到了之后，定时（默认30秒）去检测前置数据是否就绪，直到数据就绪为止。

就是这个意思，所以我们设计了Delay
