### ISSUE TITLE
分布式标记大数据

### ISSUE THREAD

**Issue by lanseyouling** [NewLifeX/AntJob#3]
需求：
我有个2018年12万个病人列表，现有个需求，要对这12万病人的进行标记哪些病人是使用过药品的病人，哪些病人用过基础药物，哪些用过抗生素，是几级抗生素。哪些病人做过四级手术
2018年的12万病人的费用明细表有3000万数据
但这张费用表存了1.5亿的数据

比如我有3500台客户机，有100000个任务让他们去做，是客户机自己主动上报结果，还是由发消息的总线程负责收集结果并入库

**Comment by nnhy** [comment]
作业流程大概这样：
list=select * from source where time>=@startTime and time <@endTime 
c1=list.where(e.c1).sum()
c2=list.where(e.c2).sum()
cn=list.where(e.cn).sum()
update dest set total=total+@c1 where c=c1

**Comment by nnhy** [comment]
蚂蚁调度AntJob-分布式任务调度系统 · 语雀
https://www.yuque.com/smartstone/blood/antjob
